/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIdImport } from './routes/profile/$id'
import { Route as UserAddUserImport } from './routes/user/add-user'
import { Route as TableUserTableImport } from './routes/table/user-table'
import { Route as ProfileViewProfileImport } from './routes/profile/view-profile'
import { Route as LoginLoginUserImport } from './routes/login/login-user'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserAddUserRoute = UserAddUserImport.update({
  id: '/user/add-user',
  path: '/user/add-user',
  getParentRoute: () => rootRoute,
} as any)

const TableUserTableRoute = TableUserTableImport.update({
  id: '/table/user-table',
  path: '/table/user-table',
  getParentRoute: () => rootRoute,
} as any)

const ProfileViewProfileRoute = ProfileViewProfileImport.update({
  id: '/profile/view-profile',
  path: '/profile/view-profile',
  getParentRoute: () => rootRoute,
} as any)
const ProfileIdRoute = ProfileIdImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRoute,
} as any)

const LoginLoginUserRoute = LoginLoginUserImport.update({
  id: '/login/login-user',
  path: '/login/login-user',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdImport
      parentRoute: typeof rootRoute
    }
    '/table/user-table': {
      id: '/table/user-table'
      path: '/table/user-table'
      fullPath: '/table/user-table'
      preLoaderRoute: typeof TableUserTableImport
      parentRoute: typeof rootRoute
    }
    '/user/add-user': {
      id: '/user/add-user'
      path: '/user/add-user'
      fullPath: '/user/add-user'
      preLoaderRoute: typeof UserAddUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/profile/$id': typeof ProfileIdRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/profile/$id': typeof ProfileIdRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/profile/$id': typeof ProfileIdRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/user-table': typeof TableUserTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile/view-profile' | '/table/user-table'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/view-profile' | '/table/user-table'
  id: '__root__' | '/' | '/profile/view-profile' | '/table/user-table'
  fullPaths: '/' | '/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile/$id'
  id: '__root__' | '/' | '/profile/$id'
  fullPaths:
    | '/'
    | '/login/login-user'
    | '/profile/view-profile'
    | '/table/user-table'
    | '/user/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/login-user'
    | '/profile/view-profile'
    | '/table/user-table'
    | '/user/add-user'
  id:
    | '__root__'
    | '/'
    | '/login/login-user'
    | '/profile/view-profile'
    | '/table/user-table'
    | '/user/add-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  TableUserTableRoute: typeof TableUserTableRoute
  LoginLoginUserRoute: typeof LoginLoginUserRoute
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  TableUserTableRoute: typeof TableUserTableRoute
  UserAddUserRoute: typeof UserAddUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  TableUserTableRoute: TableUserTableRoute,
  ProfileIdRoute: ProfileIdRoute,
  LoginLoginUserRoute: LoginLoginUserRoute,
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  TableUserTableRoute: TableUserTableRoute,
  UserAddUserRoute: UserAddUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
<<<<<<< HEAD
<<<<<<< HEAD
        "/profile/view-profile",
        "/table/user-table"
=======
        "/profile/$id"
>>>>>>> sat/codeboard
=======
        "/login/login-user",
        "/profile/view-profile",
        "/table/user-table",
        "/user/add-user"
>>>>>>> features/login
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
<<<<<<< HEAD
<<<<<<< HEAD
=======
    "/login/login-user": {
      "filePath": "login/login-user.tsx"
    },
>>>>>>> features/login
    "/profile/view-profile": {
      "filePath": "profile/view-profile.tsx"
    },
    "/table/user-table": {
      "filePath": "table/user-table.tsx"
<<<<<<< HEAD
=======
    "/profile/$id": {
      "filePath": "profile/$id.tsx"
>>>>>>> sat/codeboard
=======
    },
    "/user/add-user": {
      "filePath": "user/add-user.tsx"
>>>>>>> features/login
    }
  }
}
ROUTE_MANIFEST_END */
