/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserAddUserImport } from './routes/user/add-user'
import { Route as TestingTableImport } from './routes/testing/table'
import { Route as TestingSidebarImport } from './routes/testing/sidebar'
import { Route as TestingLoginImport } from './routes/testing/login'
import { Route as TestingLocationsImport } from './routes/testing/locations'
import { Route as TestingDoctorLeaveTableImport } from './routes/testing/doctor-leave-table'
import { Route as TestingAppointmentTableImport } from './routes/testing/appointment-table'
import { Route as TableUserTableImport } from './routes/table/user-table'
import { Route as TableRecentCommitTableImport } from './routes/table/recent-commit-table'
import { Route as TableProfileTableImport } from './routes/table/profile-table'
import { Route as TableDataTableImport } from './routes/table/data-table'
import { Route as TableCommitTableImport } from './routes/table/commit-table'
import { Route as ProfileViewProfileImport } from './routes/profile/view-profile'
import { Route as CardsIdImport } from './routes/cards/$id'
import { Route as CardUsersCardImport } from './routes/card/users-card'
import { Route as CardSidebarMenuImport } from './routes/card/sidebar-menu'
import { Route as CardLoginImport } from './routes/card/login'
import { Route as CardLocationNameImport } from './routes/card/location-name'
import { Route as CardHeaderImport } from './routes/card/header'
import { Route as CardFilterImport } from './routes/card/filter'
import { Route as CardDoctorTableImport } from './routes/card/doctor-table'
import { Route as CardDoctorLeaveImport } from './routes/card/doctor-leave'
import { Route as CardAppointmentScreenImport } from './routes/card/appointment-screen'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserAddUserRoute = UserAddUserImport.update({
  id: '/user/add-user',
  path: '/user/add-user',
  getParentRoute: () => rootRoute,
} as any)

const TestingTableRoute = TestingTableImport.update({
  id: '/testing/table',
  path: '/testing/table',
  getParentRoute: () => rootRoute,
} as any)

const TestingSidebarRoute = TestingSidebarImport.update({
  id: '/testing/sidebar',
  path: '/testing/sidebar',
  getParentRoute: () => rootRoute,
} as any)

const TestingLoginRoute = TestingLoginImport.update({
  id: '/testing/login',
  path: '/testing/login',
  getParentRoute: () => rootRoute,
} as any)

const TestingLocationsRoute = TestingLocationsImport.update({
  id: '/testing/locations',
  path: '/testing/locations',
  getParentRoute: () => rootRoute,
} as any)

const TestingDoctorLeaveTableRoute = TestingDoctorLeaveTableImport.update({
  id: '/testing/doctor-leave-table',
  path: '/testing/doctor-leave-table',
  getParentRoute: () => rootRoute,
} as any)

const TestingAppointmentTableRoute = TestingAppointmentTableImport.update({
  id: '/testing/appointment-table',
  path: '/testing/appointment-table',
  getParentRoute: () => rootRoute,
} as any)

const TableUserTableRoute = TableUserTableImport.update({
  id: '/table/user-table',
  path: '/table/user-table',
  getParentRoute: () => rootRoute,
} as any)

const TableRecentCommitTableRoute = TableRecentCommitTableImport.update({
  id: '/table/recent-commit-table',
  path: '/table/recent-commit-table',
  getParentRoute: () => rootRoute,
} as any)

const TableProfileTableRoute = TableProfileTableImport.update({
  id: '/table/profile-table',
  path: '/table/profile-table',
  getParentRoute: () => rootRoute,
} as any)

const TableDataTableRoute = TableDataTableImport.update({
  id: '/table/data-table',
  path: '/table/data-table',
  getParentRoute: () => rootRoute,
} as any)

const TableCommitTableRoute = TableCommitTableImport.update({
  id: '/table/commit-table',
  path: '/table/commit-table',
  getParentRoute: () => rootRoute,
} as any)

const ProfileViewProfileRoute = ProfileViewProfileImport.update({
  id: '/profile/view-profile',
  path: '/profile/view-profile',
  getParentRoute: () => rootRoute,
} as any)

const CardsIdRoute = CardsIdImport.update({
  id: '/cards/$id',
  path: '/cards/$id',
  getParentRoute: () => rootRoute,
} as any)

const CardUsersCardRoute = CardUsersCardImport.update({
  id: '/card/users-card',
  path: '/card/users-card',
  getParentRoute: () => rootRoute,
} as any)

const CardSidebarMenuRoute = CardSidebarMenuImport.update({
  id: '/card/sidebar-menu',
  path: '/card/sidebar-menu',
  getParentRoute: () => rootRoute,
} as any)

const CardLoginRoute = CardLoginImport.update({
  id: '/card/login',
  path: '/card/login',
  getParentRoute: () => rootRoute,
} as any)

const CardLocationNameRoute = CardLocationNameImport.update({
  id: '/card/location-name',
  path: '/card/location-name',
  getParentRoute: () => rootRoute,
} as any)

const CardHeaderRoute = CardHeaderImport.update({
  id: '/card/header',
  path: '/card/header',
  getParentRoute: () => rootRoute,
} as any)

const CardFilterRoute = CardFilterImport.update({
  id: '/card/filter',
  path: '/card/filter',
  getParentRoute: () => rootRoute,
} as any)

const CardDoctorTableRoute = CardDoctorTableImport.update({
  id: '/card/doctor-table',
  path: '/card/doctor-table',
  getParentRoute: () => rootRoute,
} as any)

const CardDoctorLeaveRoute = CardDoctorLeaveImport.update({
  id: '/card/doctor-leave',
  path: '/card/doctor-leave',
  getParentRoute: () => rootRoute,
} as any)

const CardAppointmentScreenRoute = CardAppointmentScreenImport.update({
  id: '/card/appointment-screen',
  path: '/card/appointment-screen',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/card/appointment-screen': {
      id: '/card/appointment-screen'
      path: '/card/appointment-screen'
      fullPath: '/card/appointment-screen'
      preLoaderRoute: typeof CardAppointmentScreenImport
      parentRoute: typeof rootRoute
    }
    '/card/doctor-leave': {
      id: '/card/doctor-leave'
      path: '/card/doctor-leave'
      fullPath: '/card/doctor-leave'
      preLoaderRoute: typeof CardDoctorLeaveImport
      parentRoute: typeof rootRoute
    }
    '/card/doctor-table': {
      id: '/card/doctor-table'
      path: '/card/doctor-table'
      fullPath: '/card/doctor-table'
      preLoaderRoute: typeof CardDoctorTableImport
      parentRoute: typeof rootRoute
    }
    '/card/filter': {
      id: '/card/filter'
      path: '/card/filter'
      fullPath: '/card/filter'
      preLoaderRoute: typeof CardFilterImport
      parentRoute: typeof rootRoute
    }
    '/card/header': {
      id: '/card/header'
      path: '/card/header'
      fullPath: '/card/header'
      preLoaderRoute: typeof CardHeaderImport
      parentRoute: typeof rootRoute
    }
    '/card/location-name': {
      id: '/card/location-name'
      path: '/card/location-name'
      fullPath: '/card/location-name'
      preLoaderRoute: typeof CardLocationNameImport
      parentRoute: typeof rootRoute
    }
    '/card/login': {
      id: '/card/login'
      path: '/card/login'
      fullPath: '/card/login'
      preLoaderRoute: typeof CardLoginImport
      parentRoute: typeof rootRoute
    }
    '/card/sidebar-menu': {
      id: '/card/sidebar-menu'
      path: '/card/sidebar-menu'
      fullPath: '/card/sidebar-menu'
      preLoaderRoute: typeof CardSidebarMenuImport
      parentRoute: typeof rootRoute
    }
    '/card/users-card': {
      id: '/card/users-card'
      path: '/card/users-card'
      fullPath: '/card/users-card'
      preLoaderRoute: typeof CardUsersCardImport
      parentRoute: typeof rootRoute
    }
    '/cards/$id': {
      id: '/cards/$id'
      path: '/cards/$id'
      fullPath: '/cards/$id'
      preLoaderRoute: typeof CardsIdImport
      parentRoute: typeof rootRoute
    }
    '/profile/view-profile': {
      id: '/profile/view-profile'
      path: '/profile/view-profile'
      fullPath: '/profile/view-profile'
      preLoaderRoute: typeof ProfileViewProfileImport
      parentRoute: typeof rootRoute
    }
    '/table/commit-table': {
      id: '/table/commit-table'
      path: '/table/commit-table'
      fullPath: '/table/commit-table'
      preLoaderRoute: typeof TableCommitTableImport
      parentRoute: typeof rootRoute
    }
    '/table/data-table': {
      id: '/table/data-table'
      path: '/table/data-table'
      fullPath: '/table/data-table'
      preLoaderRoute: typeof TableDataTableImport
      parentRoute: typeof rootRoute
    }
    '/table/profile-table': {
      id: '/table/profile-table'
      path: '/table/profile-table'
      fullPath: '/table/profile-table'
      preLoaderRoute: typeof TableProfileTableImport
      parentRoute: typeof rootRoute
    }
    '/table/recent-commit-table': {
      id: '/table/recent-commit-table'
      path: '/table/recent-commit-table'
      fullPath: '/table/recent-commit-table'
      preLoaderRoute: typeof TableRecentCommitTableImport
      parentRoute: typeof rootRoute
    }
    '/table/user-table': {
      id: '/table/user-table'
      path: '/table/user-table'
      fullPath: '/table/user-table'
      preLoaderRoute: typeof TableUserTableImport
      parentRoute: typeof rootRoute
    }
    '/testing/appointment-table': {
      id: '/testing/appointment-table'
      path: '/testing/appointment-table'
      fullPath: '/testing/appointment-table'
      preLoaderRoute: typeof TestingAppointmentTableImport
      parentRoute: typeof rootRoute
    }
    '/testing/doctor-leave-table': {
      id: '/testing/doctor-leave-table'
      path: '/testing/doctor-leave-table'
      fullPath: '/testing/doctor-leave-table'
      preLoaderRoute: typeof TestingDoctorLeaveTableImport
      parentRoute: typeof rootRoute
    }
    '/testing/locations': {
      id: '/testing/locations'
      path: '/testing/locations'
      fullPath: '/testing/locations'
      preLoaderRoute: typeof TestingLocationsImport
      parentRoute: typeof rootRoute
    }
    '/testing/login': {
      id: '/testing/login'
      path: '/testing/login'
      fullPath: '/testing/login'
      preLoaderRoute: typeof TestingLoginImport
      parentRoute: typeof rootRoute
    }
    '/testing/sidebar': {
      id: '/testing/sidebar'
      path: '/testing/sidebar'
      fullPath: '/testing/sidebar'
      preLoaderRoute: typeof TestingSidebarImport
      parentRoute: typeof rootRoute
    }
    '/testing/table': {
      id: '/testing/table'
      path: '/testing/table'
      fullPath: '/testing/table'
      preLoaderRoute: typeof TestingTableImport
      parentRoute: typeof rootRoute
    }
    '/user/add-user': {
      id: '/user/add-user'
      path: '/user/add-user'
      fullPath: '/user/add-user'
      preLoaderRoute: typeof UserAddUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/card/appointment-screen': typeof CardAppointmentScreenRoute
  '/card/doctor-leave': typeof CardDoctorLeaveRoute
  '/card/doctor-table': typeof CardDoctorTableRoute
  '/card/filter': typeof CardFilterRoute
  '/card/header': typeof CardHeaderRoute
  '/card/location-name': typeof CardLocationNameRoute
  '/card/login': typeof CardLoginRoute
  '/card/sidebar-menu': typeof CardSidebarMenuRoute
  '/card/users-card': typeof CardUsersCardRoute
  '/cards/$id': typeof CardsIdRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/commit-table': typeof TableCommitTableRoute
  '/table/data-table': typeof TableDataTableRoute
  '/table/profile-table': typeof TableProfileTableRoute
  '/table/recent-commit-table': typeof TableRecentCommitTableRoute
  '/table/user-table': typeof TableUserTableRoute
  '/testing/appointment-table': typeof TestingAppointmentTableRoute
  '/testing/doctor-leave-table': typeof TestingDoctorLeaveTableRoute
  '/testing/locations': typeof TestingLocationsRoute
  '/testing/login': typeof TestingLoginRoute
  '/testing/sidebar': typeof TestingSidebarRoute
  '/testing/table': typeof TestingTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/card/appointment-screen': typeof CardAppointmentScreenRoute
  '/card/doctor-leave': typeof CardDoctorLeaveRoute
  '/card/doctor-table': typeof CardDoctorTableRoute
  '/card/filter': typeof CardFilterRoute
  '/card/header': typeof CardHeaderRoute
  '/card/location-name': typeof CardLocationNameRoute
  '/card/login': typeof CardLoginRoute
  '/card/sidebar-menu': typeof CardSidebarMenuRoute
  '/card/users-card': typeof CardUsersCardRoute
  '/cards/$id': typeof CardsIdRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/commit-table': typeof TableCommitTableRoute
  '/table/data-table': typeof TableDataTableRoute
  '/table/profile-table': typeof TableProfileTableRoute
  '/table/recent-commit-table': typeof TableRecentCommitTableRoute
  '/table/user-table': typeof TableUserTableRoute
  '/testing/appointment-table': typeof TestingAppointmentTableRoute
  '/testing/doctor-leave-table': typeof TestingDoctorLeaveTableRoute
  '/testing/locations': typeof TestingLocationsRoute
  '/testing/login': typeof TestingLoginRoute
  '/testing/sidebar': typeof TestingSidebarRoute
  '/testing/table': typeof TestingTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/card/appointment-screen': typeof CardAppointmentScreenRoute
  '/card/doctor-leave': typeof CardDoctorLeaveRoute
  '/card/doctor-table': typeof CardDoctorTableRoute
  '/card/filter': typeof CardFilterRoute
  '/card/header': typeof CardHeaderRoute
  '/card/location-name': typeof CardLocationNameRoute
  '/card/login': typeof CardLoginRoute
  '/card/sidebar-menu': typeof CardSidebarMenuRoute
  '/card/users-card': typeof CardUsersCardRoute
  '/cards/$id': typeof CardsIdRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/table/commit-table': typeof TableCommitTableRoute
  '/table/data-table': typeof TableDataTableRoute
  '/table/profile-table': typeof TableProfileTableRoute
  '/table/recent-commit-table': typeof TableRecentCommitTableRoute
  '/table/user-table': typeof TableUserTableRoute
  '/testing/appointment-table': typeof TestingAppointmentTableRoute
  '/testing/doctor-leave-table': typeof TestingDoctorLeaveTableRoute
  '/testing/locations': typeof TestingLocationsRoute
  '/testing/login': typeof TestingLoginRoute
  '/testing/sidebar': typeof TestingSidebarRoute
  '/testing/table': typeof TestingTableRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/card/appointment-screen'
    | '/card/doctor-leave'
    | '/card/doctor-table'
    | '/card/filter'
    | '/card/header'
    | '/card/location-name'
    | '/card/login'
    | '/card/sidebar-menu'
    | '/card/users-card'
    | '/cards/$id'
    | '/profile/view-profile'
    | '/table/commit-table'
    | '/table/data-table'
    | '/table/profile-table'
    | '/table/recent-commit-table'
    | '/table/user-table'
    | '/testing/appointment-table'
    | '/testing/doctor-leave-table'
    | '/testing/locations'
    | '/testing/login'
    | '/testing/sidebar'
    | '/testing/table'
    | '/user/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/card/appointment-screen'
    | '/card/doctor-leave'
    | '/card/doctor-table'
    | '/card/filter'
    | '/card/header'
    | '/card/location-name'
    | '/card/login'
    | '/card/sidebar-menu'
    | '/card/users-card'
    | '/cards/$id'
    | '/profile/view-profile'
    | '/table/commit-table'
    | '/table/data-table'
    | '/table/profile-table'
    | '/table/recent-commit-table'
    | '/table/user-table'
    | '/testing/appointment-table'
    | '/testing/doctor-leave-table'
    | '/testing/locations'
    | '/testing/login'
    | '/testing/sidebar'
    | '/testing/table'
    | '/user/add-user'
  id:
    | '__root__'
    | '/'
    | '/card/appointment-screen'
    | '/card/doctor-leave'
    | '/card/doctor-table'
    | '/card/filter'
    | '/card/header'
    | '/card/location-name'
    | '/card/login'
    | '/card/sidebar-menu'
    | '/card/users-card'
    | '/cards/$id'
    | '/profile/view-profile'
    | '/table/commit-table'
    | '/table/data-table'
    | '/table/profile-table'
    | '/table/recent-commit-table'
    | '/table/user-table'
    | '/testing/appointment-table'
    | '/testing/doctor-leave-table'
    | '/testing/locations'
    | '/testing/login'
    | '/testing/sidebar'
    | '/testing/table'
    | '/user/add-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardAppointmentScreenRoute: typeof CardAppointmentScreenRoute
  CardDoctorLeaveRoute: typeof CardDoctorLeaveRoute
  CardDoctorTableRoute: typeof CardDoctorTableRoute
  CardFilterRoute: typeof CardFilterRoute
  CardHeaderRoute: typeof CardHeaderRoute
  CardLocationNameRoute: typeof CardLocationNameRoute
  CardLoginRoute: typeof CardLoginRoute
  CardSidebarMenuRoute: typeof CardSidebarMenuRoute
  CardUsersCardRoute: typeof CardUsersCardRoute
  CardsIdRoute: typeof CardsIdRoute
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  TableCommitTableRoute: typeof TableCommitTableRoute
  TableDataTableRoute: typeof TableDataTableRoute
  TableProfileTableRoute: typeof TableProfileTableRoute
  TableRecentCommitTableRoute: typeof TableRecentCommitTableRoute
  TableUserTableRoute: typeof TableUserTableRoute
  TestingAppointmentTableRoute: typeof TestingAppointmentTableRoute
  TestingDoctorLeaveTableRoute: typeof TestingDoctorLeaveTableRoute
  TestingLocationsRoute: typeof TestingLocationsRoute
  TestingLoginRoute: typeof TestingLoginRoute
  TestingSidebarRoute: typeof TestingSidebarRoute
  TestingTableRoute: typeof TestingTableRoute
  UserAddUserRoute: typeof UserAddUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardAppointmentScreenRoute: CardAppointmentScreenRoute,
  CardDoctorLeaveRoute: CardDoctorLeaveRoute,
  CardDoctorTableRoute: CardDoctorTableRoute,
  CardFilterRoute: CardFilterRoute,
  CardHeaderRoute: CardHeaderRoute,
  CardLocationNameRoute: CardLocationNameRoute,
  CardLoginRoute: CardLoginRoute,
  CardSidebarMenuRoute: CardSidebarMenuRoute,
  CardUsersCardRoute: CardUsersCardRoute,
  CardsIdRoute: CardsIdRoute,
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  TableCommitTableRoute: TableCommitTableRoute,
  TableDataTableRoute: TableDataTableRoute,
  TableProfileTableRoute: TableProfileTableRoute,
  TableRecentCommitTableRoute: TableRecentCommitTableRoute,
  TableUserTableRoute: TableUserTableRoute,
  TestingAppointmentTableRoute: TestingAppointmentTableRoute,
  TestingDoctorLeaveTableRoute: TestingDoctorLeaveTableRoute,
  TestingLocationsRoute: TestingLocationsRoute,
  TestingLoginRoute: TestingLoginRoute,
  TestingSidebarRoute: TestingSidebarRoute,
  TestingTableRoute: TestingTableRoute,
  UserAddUserRoute: UserAddUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/card/appointment-screen",
        "/card/doctor-leave",
        "/card/doctor-table",
        "/card/filter",
        "/card/header",
        "/card/location-name",
        "/card/login",
        "/card/sidebar-menu",
        "/card/users-card",
        "/cards/$id",
        "/profile/view-profile",
        "/table/commit-table",
        "/table/data-table",
        "/table/profile-table",
        "/table/recent-commit-table",
        "/table/user-table",
        "/testing/appointment-table",
        "/testing/doctor-leave-table",
        "/testing/locations",
        "/testing/login",
        "/testing/sidebar",
        "/testing/table",
        "/user/add-user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/card/appointment-screen": {
      "filePath": "card/appointment-screen.tsx"
    },
    "/card/doctor-leave": {
      "filePath": "card/doctor-leave.tsx"
    },
    "/card/doctor-table": {
      "filePath": "card/doctor-table.tsx"
    },
    "/card/filter": {
      "filePath": "card/filter.tsx"
    },
    "/card/header": {
      "filePath": "card/header.tsx"
    },
    "/card/location-name": {
      "filePath": "card/location-name.tsx"
    },
    "/card/login": {
      "filePath": "card/login.tsx"
    },
    "/card/sidebar-menu": {
      "filePath": "card/sidebar-menu.tsx"
    },
    "/card/users-card": {
      "filePath": "card/users-card.tsx"
    },
    "/cards/$id": {
      "filePath": "cards/$id.tsx"
    },
    "/profile/view-profile": {
      "filePath": "profile/view-profile.tsx"
    },
    "/table/commit-table": {
      "filePath": "table/commit-table.tsx"
    },
    "/table/data-table": {
      "filePath": "table/data-table.tsx"
    },
    "/table/profile-table": {
      "filePath": "table/profile-table.tsx"
    },
    "/table/recent-commit-table": {
      "filePath": "table/recent-commit-table.tsx"
    },
    "/table/user-table": {
      "filePath": "table/user-table.tsx"
    },
    "/testing/appointment-table": {
      "filePath": "testing/appointment-table.tsx"
    },
    "/testing/doctor-leave-table": {
      "filePath": "testing/doctor-leave-table.tsx"
    },
    "/testing/locations": {
      "filePath": "testing/locations.tsx"
    },
    "/testing/login": {
      "filePath": "testing/login.tsx"
    },
    "/testing/sidebar": {
      "filePath": "testing/sidebar.tsx"
    },
    "/testing/table": {
      "filePath": "testing/table.tsx"
    },
    "/user/add-user": {
      "filePath": "user/add-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
