/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UserAddUserImport } from './routes/user/add-user'
import { Route as ProfileViewProfileImport } from './routes/profile/view-profile'
import { Route as LoginLoginUserImport } from './routes/login/login-user'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserAddUserRoute = UserAddUserImport.update({
  id: '/user/add-user',
  path: '/user/add-user',
  getParentRoute: () => rootRoute,
} as any)

const ProfileViewProfileRoute = ProfileViewProfileImport.update({
  id: '/profile/view-profile',
  path: '/profile/view-profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginLoginUserRoute = LoginLoginUserImport.update({
  id: '/login/login-user',
  path: '/login/login-user',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login/login-user': {
      id: '/login/login-user'
      path: '/login/login-user'
      fullPath: '/login/login-user'
      preLoaderRoute: typeof LoginLoginUserImport
      parentRoute: typeof rootRoute
    }
    '/profile/view-profile': {
      id: '/profile/view-profile'
      path: '/profile/view-profile'
      fullPath: '/profile/view-profile'
      preLoaderRoute: typeof ProfileViewProfileImport
      parentRoute: typeof rootRoute
    }
    '/user/add-user': {
      id: '/user/add-user'
      path: '/user/add-user'
      fullPath: '/user/add-user'
      preLoaderRoute: typeof UserAddUserImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login/login-user': typeof LoginLoginUserRoute
  '/profile/view-profile': typeof ProfileViewProfileRoute
  '/user/add-user': typeof UserAddUserRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/login-user'
    | '/profile/view-profile'
    | '/user/add-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login/login-user' | '/profile/view-profile' | '/user/add-user'
  id:
    | '__root__'
    | '/'
    | '/login/login-user'
    | '/profile/view-profile'
    | '/user/add-user'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLoginUserRoute: typeof LoginLoginUserRoute
  ProfileViewProfileRoute: typeof ProfileViewProfileRoute
  UserAddUserRoute: typeof UserAddUserRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLoginUserRoute: LoginLoginUserRoute,
  ProfileViewProfileRoute: ProfileViewProfileRoute,
  UserAddUserRoute: UserAddUserRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login/login-user",
        "/profile/view-profile",
        "/user/add-user"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login/login-user": {
      "filePath": "login/login-user.tsx"
    },
    "/profile/view-profile": {
      "filePath": "profile/view-profile.tsx"
    },
    "/user/add-user": {
      "filePath": "user/add-user.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
